<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Com.SomeGameCorp.Bylinjen.Application.Newsletter</RootNamespace>
    <AssemblyName>Com.SomeGameCorp.Bylinjen.Application.Newsletter</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
